frigate:
  frigate_url: http://192.168.1.75:5000
  mqtt_server: 192.168.1.75
  mqtt_auth: false
  mqtt_username: username
  mqtt_password: password
  main_topic: frigate
  camera:
    - birdcam
  object: bird
classification:
  model: model.tflite
  threshold: 0.7
webui:
  port: 7766
  host: 0.0.0.0
api:
  port: 8000
  host: 0.0.0.0
  debug: false
file_watcher:
  watch_directory: ./watch
  threshold: 0.7
  use_common_names: true
  rename_files: true